#配置文件 Tpa Config ver 1.2.0 by RENaa_FD

# 启用tpa玩家名称自动补全
# 用于一些不支持非完整玩家名TPA的插件
# 这个功能甚至对Java版有辅助作用
auto-completion-player-name: true

# 启用数据统计
metrics: true

# tpa相关的命令
tpa-command: "tpa"
tpa-here-command: "tpahere"
accept-command: "tpaccept"
deny-command: "tpadeny"

# 传送接受菜单的图标
accept-form-icon: "textures/ui/realms_green_check.png"
deny-form-icon: "textures/ui/realms_red_x.png"




