name: Tpa
version: '${project.version}'
main: ren.rymc.tpa.Tpa
api-version: 1.13
depend: [ floodgate ]
authors: [ RENaa_FD ]
description: "任渊TPA基岩版兼容插件"
commands:
  tpaui:
    description: "打开tpaui"
    usage: ""
permissions:
  tpaui.admin:
    description: "tpaui主权限"
    default: op